#!/usr/bin/bash

set -o errexit

export LC_ALL=en_US.utf8
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8

# RC 5.0.x
ROCKET_CHAT_VERSION="5.0.4"
ROCKET_CHAT_PATCHED=true
NODE_JS_VERSION="14.19.3"
MONGO_VERSION="4.4"

# RC 4.5.x (without fully featured)
# ROCKET_CHAT_VERSION="4.5.7"
# ROCKET_CHAT_PATCHED=""
# NODE_JS_VERSION="14.18.3"
# MONGO_VERSION="4.4"

# RC 3.18.x (with id mapping)
# ROCKET_CHAT_VERSION="3.18.7"
# ROCKET_CHAT_PATCHED=""
# NODE_JS_VERSION="12.22.1"
# MONGO_VERSION="4.2"

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echo "* Remove apt-get workaround"
rm /usr/local/bin/apt-get || true

echo "* Get latest"
export DEBIAN_FRONTEND=noninteractive
apt-get -y update
yes no | apt-get -y upgrade
apt-get -y dist-upgrade

echo "* Setup nginx"
ln -nfs /etc/nginx/sites-available/rocketchat /etc/nginx/sites-enabled/rocketchat
mkdir -p /etc/nginx/ssl
chmod 0500 /etc/nginx/ssl
/usr/local/bin/ssl-selfsigned.sh -d /etc/nginx/ssl -f rocketchat
mv /usr/local/var/tmp/nginx_service /usr/lib/systemd/system/nginx.service
systemctl daemon-reload
# service nginx restart

echo "* Setup mongodb v${MONGO_VERSION}"
if [[ "${MONGO_VERSION}" = "4.2" ]]; then
  curl -fsSL https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add - || true
  echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list
elif [[ "${MONGO_VERSION}" = "4.4" ]]; then
  curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - || true
  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
else
  echo "ERROR: mongodb-version not found"
  exit 1
fi

apt-get -y update
apt-get -y install mongodb-org
sed -i "s/^#  engine:/  engine: wiredTiger/" /etc/mongod.conf
sed -i "s/^#replication:/replication:\n  replSetName: rs01/" /etc/mongod.conf

echo "* Setup node"
apt-get -y install npm
npm install -g inherits n
/usr/local/bin/n $NODE_JS_VERSION
# npm install npm@latest -g

echo "* Setup rocket-chat"
addgroup rocket
adduser --disabled-password --system --quiet --home /var/www/rocket --shell /usr/bin/bash rocket
adduser rocket rocket
mkdir -p /var/www/rocket
if [[ -z "${ROCKET_CHAT_PATCHED}" ]]; then
  curl -L -s "https://download.qutic.com/src/rocket-chat/rocket.chat-${ROCKET_CHAT_VERSION}.tgz" | tar xz -C /var/www/rocket --strip-components=1
else
  curl -L -s "https://download.qutic.com/src/rocket-chat/rocket.chat-${ROCKET_CHAT_VERSION}-patched.tar.bz2" | tar xj -C /var/www/rocket --strip-components=2
fi
chown -R rocket:rocket /var/www/rocket
chmod 0644 /var/www/rocket/programs/server/*.json
su - rocket -c "cd /var/www/rocket/programs/server && npm install"

echo "* Setup rocket-chat service"
cp /usr/local/var/tmp/nginx.conf /etc/nginx/nginx.conf
cp /usr/local/var/tmp/rocketchat_service /etc/systemd/system/rocketchat.service

echo "* Disable and remove rpcbind"
apt-get -y remove rpcbind || true
systemctl stop rpcbind.service
systemctl disable rpcbind.service

echo "* Disable nfs-client"
systemctl unmask nfs-client.target
systemctl disable nfs-client.target

echo "* Disable ssh"
systemctl stop ssh
systemctl disable ssh

echo "* Create bash-history"
cat >> /root/.bash_history << EOF
systemctl restart mongod
systemctl status mongod
systemctl edit --full rocketchat
systemctl daemon-reload
systemctl reset-failed rocketchat.service
systemctl restart rocketchat
systemctl status rocketchat
systemctl reload nginx
journalctl --since $(date '+%Y-%m-%d')
EOF

echo "* Ensure bootstrap will run next time"
rm -rf /var/lib/bootstrap

echo "* Cleaning up."
apt-get -y purge git make gcc g++ build-essential
apt-get -y autoremove
rm -rf /usr/local/var/tmp/*
rm /var/log/syslog || true
touch /var/log/syslog || true
rm /root/customize
history -c
