#!/bin/bash

set -o errexit

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MUNIN_PLUGINS="
ps_node
ps_nginx
"

echo "* Activate munin plugins"
/usr/local/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Get latest packages"
apt-get update
apt-get -y upgrade

echo "* Setup nginx"
mv /usr/local/var/tmp/rocketchat /etc/nginx/sites-available/rocketchat
ln -nfs /etc/nginx/sites-available/rocketchat /etc/nginx/sites-enabled/rocketchat
mkdir -p /etc/nginx/ssl
chmod 0500 /etc/nginx/ssl
/usr/local/bin/ssl-selfsigned.sh -d /etc/nginx/ssl -f rocketchat
# service nginx restart

echo "* Setup node"
# http://linuxbsdos.com/2017/06/26/how-to-install-node-js-lts-on-debian-9-stretch/
curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
apt-get update
apt -qq install nodejs
npm install -g n
n 8.11.4

# curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
# echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
# sudo apt-get update && sudo apt-get install yarn

echo "* Setup rocket-chat"
adduser --disabled-password --system --quiet --home /var/www/rocket rocket
mkdir -p /var/www/rocket
curl -L -s https://releases.rocket.chat/latest/download | tar xz -C /var/www/rocket --strip-components=1
cd /var/www/rocket
(cd programs/server && npm install)
chown -R rocket:rocket /var/www/rocket*

echo "* Setup rocket-chat service"
cp /usr/local/var/tmp/rocketchat.service /etc/systemd/system/rocketchat.service
systemctl daemon-reload
systemctl enable rocketchat.service
# systemctl start rocketchat

echo "* Cleaning up."
history -c
